

#  D
#  DATABASE
DATABASE_DRIVER = 'mongodb'
DATABASE_DATABASE = "LianJia"  # for sqlite, use this as filepath
DATABASE_HOST = "47.105.165.81"
DATABASE_PORT = 27170
DATABASE_USER = 'test'
DATABASE_PASSWORD = 'test123'
DATABASE_AUTH = "LianJia"