

#  D
#  DATABASE
DATABASE_DRIVER = 'mongodb'
DATABASE_DATABASE = "stock"  # for sqlite, use this as filepath
# DATABASE_HOST = "47.105.165.81"
DATABASE_HOST = "192.168.50.225"

# DATABASE_PORT = 27170
DATABASE_PORT = 27017
DATABASE_USER = 'stock'
DATABASE_PASSWORD = 'stock'
DATABASE_AUTH = "stock"


# E
EVENT_TICK = "eTick."
EVENT_TRADE = "eTrade."
EVENT_ORDER = "eOrder."
EVENT_POSITION = "ePosition."
EVENT_ACCOUNT = "eAccount."
EVENT_CONTRACT = "eContract."
EVENT_LOG = "eLog"

# F
FONT_FAMILY= "Arial"
FONT_SIZE = 12